name: 'pr-comment'
description: 'Adds PR changes as comment'

inputs:
  owner:
    description: 'The owner of the repository (user or org)'
    required: true
  repo:
    description: 'The repository name'
    requiered: true
  pr_number:
    description: 'The numberof the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: node20
  main: dist/index.js
